#!/bin/bash

#BSUB -J cpu_transolver      # Job name
#BSUB -q 1t75c       # Queue name (change if needed)
#BSUB -n 36                           # Number of CPU cores
#BSUB -R "span[ptile=36]"
#BSUB -oo logs/out_%J.log             # Standard output (%J = job ID)
#BSUB -eo logs/err_%J.log             # Standard error
#BSUB -env "all"                      # Export your current environment

# -------------------------------
# Load environment and run script
# -------------------------------

echo "Starting DrivAerNet training on CPU nodes..."
echo "Running on host: $(hostname)"
echo "Job ID: $LSB_JOBID"
echo "Requested CPUs: $LSB_CPU_REQ"

# Activate d2l
source ~/lib/miniconda3/etc/profile.d/conda.sh
conda activate d2l


# Launch .py file
#python ~/tmp/ab-ubt_v2/test_model.py
python main_cpu.py
#python train.py

# Remove old logs but keep the ones for this job
# find ./logs/ -name '*.log' ! -name "*_${LSB_JOBID}*.log" -delete
#1t81c
#2t50c
#1t75c
#v3-6t
#73x
