[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "p3d-surrogate"
version = "0.0.4"
description = "P3D: Highly Scalable Neural Surrogates for 3D Physics Simulations"
readme = "README.MD"
authors = [
    { name = "Benjamin Holzschuh", email = "benjamin.holzschuh@tum.de" },
]
license = { text = "MIT" }
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "einops>=0.8.1",
    "diffusers>=0.28.2",
    "numpy>=1.26.4",
    "transformers>=4.42.3",
    "timm>=1.0.12",
    "ipykernel>=7.2.0",
    "vape4d",
    "matplotlib"
]

[project.urls]
Homepage = "https://akanota.github.io/p3d/"
Repository = "https://github.com/tum-pbs/P3D"

[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | docs
  )/
)
'''

[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)
include = ["p3d*"]  # package names should match these glob patterns (["*"] by default)
exclude = []  # exclude packages matching these glob patterns (empty by default)
namespaces = false  # to disable scanning PEP 420 namespaces (true by default)
