python ./run_pipeline.py \
    --stages train \
    --exp_name "Test" \
    --dataset_path "/work/mae-zhangbj/DrivAriNet_dataset/Pressure_Field/small_samples/Pressure_VTK" \
    --subset_dir "/work/mae-zhangbj/ML_Turbulent/Current_Work/Pressure_Field/train_val_test_splits" \
    --cache_dir "/work/mae-zhangbj/DrivAriNet_dataset/Pressure_Field/small_samples/Cache_data" \
    --num_points 10000 \
    --num_workers 1 \
    --batch_size 6 \
    --epochs 10 \
    --test_only 0 \
    --gpus "0" 
